package techjokes2015.wayneient.com.techjokes2015;

import java.util.Random;

/**
 * Created by Mark_1 on 12/1/14.
 */
public class JokeBook {
    //Member variables
    public String[] mJokes = {
            "Knock knock, who's there?... (very long pause)... Java",
            "A SQL query goes into a bar, walks up to two tables and asks, can I join you?",
            "how many programmers does it take to change a light bulb?: None, that's a hardware problem",
            "When your hammer is C++, everything begins to look like a thumb",
            "If you put a million monkeys at a million keyboards, one of them will eventually write a Java program; he'll be the least intelligent one",
            "Whats the object-oriented way to become wealthy?: Inheritance",
            "Programming is like sex: One mistake and you have to support something for the rest of your life",
            "How many prolog programmers does it take to change a lightbulb?: Yes",
            "To understand what recursion is, you must first understand recursion",
            "so this programmer goes out on a date with a hot chick... no really, that's the joke",
            "The fantastic element that explains the appeal of games to many developers is neither the fire-breathing monsters nor the milky-skinned, semi-clad sirens; it is the experience of carrying out a task from start to finish without any change in the user requirements",
            "There are 10 types of people in the world. Those who understand binary and those who have regular sex",
            "There are 10 types of people in the world. Those who understand binary and those who do not",
            "Don't you have something better to do?",
            "Why programmers like UNIX: unzip, strip, touch, finger, grep, mount, fsck, more, yes, fsck, fsck, umount, sleep",
            "two strings walk into a bar and sit down. The bartender says: So what'll it be? The first string says, I think I'll have a beer quag fulk boorg jdk^CjfdLk jk3s d#f67ho. Please excuse my friend, the second string says, He isn't null-terminated",
            "Unix is user friendly. It's just very particular about who its friends are",
            "A programmer puts two glasses on his bedside table before going to sleep. A full one, in case he gets thirsty, and an empty one, in case he doesn't",
            "If your mom was a collection class, her insert method would be public",
            "The C language combines all the power of assembly language with all the ease-of-use of assembly language",
            "Don't anthropomorphize computers. They hate that!",
            "ASCII stupid question, get a stupid ANSI",
            "how many Microsoft programmers does it take to change a light bulb?: none, they just make darkness a standard and tell everyone this behavior is by design",
            "How long does it take to copy a file in Vista?: Yeah, I don't know either, I'm still waiting to find out",
            "wo bytes meet. The first byte asks, Are you ill? The second byte replies, No, just feeling a bit off",
            "If the box says, This software requires Windows XP or better, does that mean it'll run on linux?",
            "What is the difference between a programmer and a non-programmer?: The non-programmer thinks a kilobyte is 1000 bytes while a programmer is convinced that a kilometer is 1024 meters",
            "A programmer is sent to the grocery store with instructions to buy butter and see whether they have eggs, if they do, then buy 10. Returning with 10 butters, the programmer says, they had eggs ",
            "If you listen to a UNIX shell, can you hear the C?",
            "Eight bytes walk into a bar. The bartender asks, Can I get you anything? Yeah, reply the bytes, Make us a double",
            "If Java is the answer, it must have been a really verbose question",
            "what do Computer Science students use for birth control?: Their personalities",
            "An infinite number of mathematicians walk into a bar. he first orders a beer, the second orders half a beer, the third orders a quarter of a beer, the fourth an eighth, and so on. he bartender looks at the line going out the door,turns to the line and says nice try, then pours two beers and walks away",
            "Smith & Wesson, the original point and click interface",
            "Why are Assembly programmers always soaking wet?: They work below C-level ",
            "In theory, there ought to be no difference between theory and practice. In practice, there is a big difference",
            "Nothing seems hard to the people who don't know what they're talking about",
            "C++ - where your friends have access to your private members",
            "99 little bugs in the code, 99 bugs in the code, fix one bug, compile again, 100 little bugs in the code.",
            "Why did the programmer quit his job?: Because he didn't get arrays",
            "XML is like violence. If it doesn't solve your problem, you're not using enough of it",
            "Why do java programmers have to wear glasses?: Because they don't see sharp",
            "Software developers like to solve problems. If there are no problems handily available, they will create their own problems",
            "I'd like to make the world a better place, but they won't give me the source code",
            "Indeed, when I design my killer language, the identifiers foo and bar will be reserved words, never used, and not even mentioned in the reference manual. Any program using one will simply dump core without comment. Multitudes will rejoice",
            "There's no place like 127.0.0.1",
            "I don't see women as objects. I consider each to be in a class of her own",
            ".NET is called .NET so that it wouldn't show up in a Unix directory listing",
            "What do you mean, it needs comments!? If it was hard to write, it should be hard to understand--why do you think we call it code???",
            "Hardware: The part of a computer that you can kick",
            "The women I went to the university with had this to say about their chances of meeting guys in our CS department: The odds are good, but the goods are odd",
            "What's the difference between Software Development and Sex?: In sex, you don't get a bonus for releasing early",
            "An optimist person will say that the glass is half-full, a pessimist person will say that the glass is half-empty, and a programmer will say that the glass is twice as large as necessary",
            "It compiles! Let's ship it",
            "In C we had to code our own bugs. In C++ we can inherit them",
            "How come there is not obfuscated Perl contest?: Because everyone would win",
            "When Shakespeare asked, To be, or not to be?, he did not provide the answer. But programming can, 2B |~ 2B = FF",
            "Documentation is like sex. When it's good, it's very good. When it's bad, it's better than nothing",
            "It's been said that if you play a windows CD backwards, you'll hear satanic chanting... but worse still, if you play it forwards, it installs windows",
            "IT is a funny industry. Can you think of any other group of people that would make an acronym as an excuse to say sexy (SCSI) and have everyone mispronounce it as scuzzy",
            "How many programmers does it take to kill a cockroach?: Two, one holds it and the other installs Windows on it",
            "Computers are high-speed idiots, programmed by low-speed idiots",
            "How many C++ programmers does it take to change a light bulb?: You’re still thinking procedurally. A properly designed light bulb object would inherit a change method from a generic light bulb class, so all you would have to do is call the light-bulb-change method",
            "JIT Happens!",
            "KDE or Gnome - it's like deciding which fat person you want to date",
            "Writing XML is like being an alcoholic. It may give you a sense of control while you're doing it, but it's only when you stop and look at what you have done that you realize how much trouble you've caused",
            "Girlfriend: Are you going to sit and type in front of that thing all day or are you going out with me? Programmer: Yes",
            "Three programmers go into a bar and sit down at a table. The first programmer holds up two fingers and says: three beers",
            "There are no shortcuts in life, unless you right click and find one...",
            "What did the Java code say to the C code?: You've got no class",
            "How many Intel hardware engineers does it take to change a lightbulb?: 1.0000000000001736442 but Its close enough for most people",
            "Program, noun: A magic spell cast upon a computer to enable it to turn input into error messages.",
            "Computers let you make more mistakes than any other invention in history. With the possible exception of handguns and tequila",
            "How many software engineers does it take to change a light bulb? None, the monitor works just fine",
            "If whitespace were truly white it would have show up on black background",
            "Software salesmen and used-car salesmen differ in that the latter know when they are lying",
            "Walking on water and developing software from a specification are easy if both are frozen, otherwise are miracles",
            "If you think C++ is not overly complicated, just what is a protected abstract virtual base pure virtual private destructor, and when was the last time you needed one?",
            "So, there were two blind programmers, however, one did C",
            "A programmer is someone who will spend 6 months writing a computer program that will save him 45 minutes",
            "The sign of a compulsive programmer is somebody who can count up to 1023 on his or her fingers...",
            "What does a computer scientist wear on Halloween?: A bit-mask",
            "Some call me '^F[a-z\'-]+$', but I have many names",
            "Who's General Failure & why's he reading my disk?",
            "Every developer starts out by being Optimistic. Optimistic programmers assume that system calls will always succeed, there is always enough memory and disk space, and there really is a Santa Claus",
            "How many IT Support people does it take to change a lightbulb?: Have you tried turning it Off and On?",
            "How many Pentium chip designers does it take to screw in a light bulb?: 0.999994637287432",
            "Programming a bombBaghdad function is immoral, a good programmer will always write a bombCity function and have Baghdad passed in as an argument",
            "If at first you don't succeed; call it version 1.0",
            "Some things Man was never meant to know. For everything else, there's Google",
            "Life would be so much easier if we only had the source code",
            "Microsoft: You've got questions. We've got dancing paperclips",
            "I had a fortune cookie the other day and it said: 'Outlook not so good'. I said:'Sure, but Microsoft ships it anyway'",
            "Feminist Unix Command: man bash",
            "All programs are poems, it's just that not all programmers are poets",
            "Administrator = Admin is traitor",
            "The trouble with programmers is that you can never tell what they're doing until it's too late",
            "Saying that Java is nice because it works on all OS's is like saying that anal sex is nice because it works on all genders",
            "Why is your kid sitting alone apart from all those other kids in the sandbox? They're all playing a computer lab and mine's trying to get Linux running",
            "When a programmer and a beggar meet, the very first question they ask each other - Which platform are you working on?",
            "2 + 2 = 5 (for large values of 2)",
            "I'm nervous about programming in an untyped language---my penmanship is awful!",
            "What happens if a pattern and an anti-pattern collide?: You get a singletonarity",
            "Java: write once, debug everywhere",
            "What do database administrators give their daughters to prevent them from having child records: Foreign Key Constraints",
            "When does a Boolean evaluated expression achieve orgasm?: After a while",
            "COBOL stands for: Compiles Only Because Of Luck",
            "Remember: there's no faster code than no code",
            "Vista: virus infected system, try apple",
            "Recursion: Definition of recursion, see recursion",
            "On a clear disk you can seek forever",
            "Why, in my day, all we had were ones and zeros, and that was on a good day. On bad days, all we had were zeros",
            "Programming really is like practicing magic. But Java is a broken wond",
            "If two people enter the elevator and three people get out on the next floor, one person must get in so the elevator is empty",
            "You had me at Hello World",
            "When I code I like to think like a computer. The problem is that computers don't think",
            "If architects built buildings the way programmers write software, the first woodpecker that came along would destroy civilization",
            "Have you heard about the constipated mathematician? He worked it out with a pencil",
            "Did you hear the one about the Windows user who's car got a flat? He spent the whole night turning on and off the car trying to fix it",
            "LISP is the acronym for Lost In Stupid Programming",
            "If we have a programming language named Java surely we need one called Monster",
            "An IPv4 address walks into a bar and says: Quick, give me a drink. I am exhausted",
            "Didn’t we run out of IPv4 jokes?",
            "Router: It hurts when IP",
            "Network prayer: Dear Lord, Please grant me the ability to punch people in the face over standard TCP/IP",
            "I have told IPv4 joke to my friend. He checked checksum and had best effort laugh",
            "The bad thing about IPv6 jokes is that nobody wants to tell them first",
            "The problem with IPv6 jokes is they’re long, obscure and no one gets them without a translation",
            "I know a great IPv6 joke, but I just don’t think you’re ready for it",
            "An IPv6 packet walks into a bar. Nobody talks to him",
            "Is smoke signal a routable protocol?",
            "I’d like to tell you the full joke about a BGP table but I don’t think you can remember it all",
            "The strange thing about BGP jokes is that they’re borderline funny but everybody repeats them anyway",
            "What did the OSPF router say to the other OSPF router?: Hello. Hello. Hello. Hello. Hello. Hello. Hello. Hello",
            "Five routers walk into a bar. Who gets the car keys?: The Designated Router",
            "Why are ASAs so noisy?: They don’t know how to ssh",
            "The great thing about HTTP Upgrade jokes is… wait, someone might be listening, come closer add I’ll whisper",
            "A bunch of TCP packets walk into a bar. The bartender says, Hang on just a second, I need to close the window.",
            "Chuck Norris doesn’t do TCP handshake – he does TCP roundhouse-kick to initiate the connection.",
            "The world is moving from IPv4 and going straight to IPv6 because Chuck Norris doesn’t like the number 5",
            "An expert is a person who has made all the mistakes which can be made",
            "I've got 2^n problems but a bit aint one",
            "I don't always test my code, but when I do, I do it in production",
            "If Windows is the solution, can we please have the problem back?",
            "Computers are like air-conditioning, they stop working properly if you open Windows",
            "What's the definition of an IT professional?: Someone who solves a problem you didn't know you had in a way you don't understand",
            "What's an IT auditor?: Someone who arrives after the battle and bayonets all the wounded",
            "Why did the IT auditor cross the road?: Because he looked in the file and that's what they did last year",
            "IT professional defined: Someone smart enough to learn how to use someone elses crap, but not smart enough to make their own crap"
    };

    //Methods
    public String getJoke(){

        String joke = "";
        Random randomGenerator = new Random();
        int randomNumber = randomGenerator.nextInt(mJokes.length);
        joke = mJokes[randomNumber];

        return joke;
    }
}
